// export const FETCH_COURSES_HOMEPAGE = "FETCH_COURSES_HOMEPAGE";
export const FETCH_COURSES = "FETCH_COURSES";
export const FETCH_COURSE_LIST = "FETCH_COURSE_LIST";
export const FETCH_COURSE_DETAIL = "FETCH_COURSE_DETAIL";
export const FETCH_CREDENTIALS = "FETCH_CREDENTIALS";
export const FETCH_COURSE_MENU = "FETCH_COURSE_MENU";